### PR TITLE
Migrate deps to go mod

### PR DESCRIPTION
**Pull request by jjcollinge**
Issue #86

### CODE REVIEW

**Comment by jjcollinge** [comment]
Sorry about the messy history - some reason I did the initial migrate on a stale branch which worked locally but failed in CI then had to fix. We can clean that up on merge if we decide to go ahead.

**Comment by lawrencegripper** [comment]
Wow this is awesome - thank. Took me a while to read up on modules stuff to be able to understand whats going on. 

One of the things I'm a bit worried about with the move, likely me being paranoid, is what happens in the `go modules` world if one of the projects dependencies github repos is removed? As Github isn't a package manager feels like this a bit of a risk. Looks like I can help my paranoia by [running this command](https://tip.golang.org/cmd/go/#hdr-Modules_and_vendoring) but yeah not sure whether it's me being overly cautious or not.

**Comment by jjcollinge** [comment]
Yh I think this is something project Athens was trying to address. Not sure how far it has progressed, will have a look.

**Comment by lawrencegripper** [comment]
Nice that sounds like it sovles the problem nicely, fingers crossed it works!

**Pull request merged**
