### PR TITLE
Dynamically size views 

### LINKED ISSUE #59: Font resizing not handling
When azbrowse starts up it fills the terminal window. When the font size in the terminal is scaled azbrowse doesn't adapt.

### PR DESCRIPTION
**Pull request by stuartleeks**
Closes #59

### CODE REVIEW

**Comment by stuartleeks** [comment]
In action:
azb-resize

**Comment by stuartleeks** [comment]
@daltskin - FYI (I think you mentioned that you wanted this recently, too)

**Comment by stuartleeks** [comment]
Added tests and cleaned up the implementation :-)

**Review by lawrencegripper — APPROVED** [review]
LGTM

**Pull request merged**
