### PR TITLE
Initial attempt at data-plane functionality for Container Registry

### PR DESCRIPTION
**Pull request by stuartleeks**
Handles GET requests for repositories, tags and manifests with support for paging.

### CODE REVIEW

**Comment by stuartleeks** [comment]
@lawrencegripper / @jjcollinge - any suggestions on how to resolve to golangci-lint error?

```internal/pkg/handlers/containerRegistry.go:443:2: S1021: should merge variable declaration with assignment on next line (gosimple)
	var itemsTemp interface{}
	^
```

If I merge the declaration into assignment (`itemsTemp := jsonResponse`) then I get fresh build errors!

```
internal/pkg/handlers/containerRegistry.go:447:24: invalid type assertion: itemsTemp.(map[string]<inter>) (non-interface type map[string]interface {} on left)
internal/pkg/handlers/containerRegistry.go:453:21: invalid type assertion: itemsTemp.([]<inter>) (non-interface type map[string]interface {} on left)
```

**Comment by stuartleeks** [comment]
I've pushed a commit that ignores the linter comment for that line :-)

**Comment by stuartleeks** [comment]
rebased and removed vendor folder

**Comment by stuartleeks** [comment]
@lawrencegripper - are you able to re-run the AzDO test?

**Comment by lawrencegripper** [comment]
On it. :)

**Comment by lawrencegripper** [comment]
Build passed. Happy for me to merge?

**Comment by stuartleeks** [comment]
You betcha 😀

**Pull request merged**
