### PR TITLE
Fix JSON formatting #161

### PR DESCRIPTION
**Pull request by jjcollinge**
Fix JSON formatting #161

Not sure this is the best way to fix, just had a quick go at getting something working. Any suggestions.

Using `style/colors.go` seemed to add a bunch of color characters so I just used the vanilla json package. Could extract this common funciton to `style/format.go` or something.

FYI: This will conflict with #165

### CODE REVIEW

**Comment by lawrencegripper** [comment]
Nice this look good to me. 

nit: Should be use the `ContentType` to only invoke the `json` formatting when the response is JSON. Keeps things cleaner if we want to add other formatters for YAML etc. 

Could move this to here: https://github.com/lawrencegripper/azbrowse/pull/166/files#diff-93ef310a1235e982e0a50912580c4827L507-L514

**Comment by jjcollinge** [comment]
> 
> 
> Nice this look good to me.
> 
> nit: Should be use the `ContentType` to only invoke the `json` formatting when the response is JSON. Keeps things cleaner if we want to add other formatters for YAML etc.
> 
> Could move this to here: https://github.com/lawrencegripper/azbrowse/pull/166/files#diff-93ef310a1235e982e0a50912580c4827L507-L514

Yeh makes sense, will update

**Comment by stuartleeks** [comment]
Just created #173 to fix up the merge conflict between this PR and #165

**Comment by jjcollinge** [comment]
FYI: I’m on holiday at the moment and don’t a have a laptop to hand to address this until next Tuesday.

**Comment by stuartleeks** [comment]
Oh wow - you've been busy on your phone then! Have a good holiday 😀

**Pull request merged**
